noun_1 = input("Give me a plural noun ")
verb = input("Give me a verb ending in ed ")
noun_2 = input("Give me another plural noun ")
noun_3 = input("Give me a noun ")
adjective = input("Give me an adjective ")
food_1 = input("Give me a type of food ")
food_2 = input("Give me another type of food ")
noun_4 = input("Give me a noun ")
noun_5 = input("and another one ")
noun_6 = input("Give me one last noun ")

print("Ice cream is a frozen dessert made from " + noun_1 + ", with added flavours and sweeteners")
print("This mixture is quickly frozen while it is " + verb + ", so that large " + noun_2 + " do not form.")
print("Some ice cream is made with " + noun_3 + " extracted from seaweed, so that it is not " + adjective)
print("There are many different flavours of ice cream, such as " + food_1 + " and " + food_2)
print("Ice cream often has things added to it for flavour, like " + noun_4 + ", " + noun_5 + " or " + noun_6)
